#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) buffer buf {
    int pixels[];
};

layout(push_constant) uniform constants {
    ivec2 dim;
};

void main() {
    if (gl_GlobalInvocationID.x >= dim.x || gl_GlobalInvocationID.y >= dim.y) {
        return;
    }

    uint pos = gl_GlobalInvocationID.y * dim.x + gl_GlobalInvocationID.x;
    pixels[pos] = int(gl_GlobalInvocationID.x);
}
